export const GET_RESULTS = "GET_RESULTS";
export const GET_RESULTS_SUCCESS = "GET_RESULTS_SUCCESS";
export const GET_RESULTS_ERROR = "GET_RESULTS_ERROR";

export const GET_SINGLE_RESULT = "GET_SINGLE_RESULT";
export const GET_SINGLE_RESULT_SUCCESS = "GET_SINGLE_RESULT_SUCCESS";
export const GET_SINGLE_RESULT_ERROR = "GET_SINGLE_RESULT_ERROR";

export const PRELOAD_SINGLE_RESULT = "PRELOAD_SINGLE_RESULT";